version: '3.5'
services:
  php:
    container_name: aulas-online-php
    image: aulas-online/php
    build: ./
    networks:
      - backend
    volumes:
      - ./:/var/www/html
    environment:
      - ENVIRONMENT=development

networks:
  backend: