version: '3.0'
services:
  web:
    container_name: php-training-web
    image: php-training/web
    depends_on:
      - php
    build: ./docker/nginx
    networks:
      - backend
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/conf:/etc/nginx/sites-available
      - ./:/var/www/html

  php:
    container_name: php-training-php
    image: php-training/php
    build: ./docker/php
    networks:
      - backend
    volumes:
      - ./:/var/www/html
    environment:
      - ENVIRONMENT=development

networks:
  backend: